export enum errorAuthSignUp {
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  USED_EMAIL_OR_PHONE_NUMBER = 'USED_EMAIL_OR_PHONE_NUMBER'
}

export enum errorVerifyOtp {
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  IS_NOT_ACCESS_TOKEN = 'IS_NOT_ACCESS_TOKEN'
}
