export const PhaseBooking = {
  CHOOSE_SERVICE: 'CHOOSE_SERVICE',
  SET_INFOR_PACKAGE: 'SET_INFOR_PACKAGE',
  CHOOSE_LOCATION: 'CHOOSE_LOCATION',
  CONFIRM_BOOK: 'CONFIRM_BOOK',
  GET_BIKER: 'GET_BIKER',
  CHOOSE_BIKER: 'CHOOSE_BIKER',
  CONFIRM_RIDE: 'CONFIRM_RIDE',
  REJECT_RIDE: 'REJECT_RIDE',
  WAIT_BIKER: 'WAIT_BIKER',
  BIKER_WAITING: 'BIKER_WAITING',
  RIDE_COMPLETE_EVENT: 'RIDE_COMPLETE_EVENT'
}

export const PhasePackage = {
  CHOOSE_SERVICE: 'CHOOSE_SERVICE'
}

export const BEFORE_RIDE = [
  PhaseBooking.CHOOSE_SERVICE,
  PhaseBooking.SET_INFOR_PACKAGE,
  PhaseBooking.CHOOSE_LOCATION,
  PhaseBooking.CONFIRM_BOOK,
  PhaseBooking.GET_BIKER,
  PhaseBooking.CHOOSE_BIKER
  // PhaseBooking.REJECT_RIDE,
  // PhaseBooking.RIDE_COMPLETE_EVENT
]

export const SERVICE = {
  DELIVERY: 'DELIVERY',
  RIDE: 'RIDE'
}

export enum PhaseBookingBeforeRide {
  CHOOSE_SERVICE = 'CHOOSE_SERVICE',
  SET_INFOR_PACKAGE = 'SET_INFOR_PACKAGE',
  CHOOSE_LOCATION = 'CHOOSE_LOCATION',
  CONFIRM_BOOK = 'CONFIRM_BOOK',
  GET_BIKER = 'GET_BIKER',
  CHOOSE_BIKER = 'CHOOSE_BIKER'
}

export enum PhaseBookingInRide {
  CONFIRM_RIDE = 'CONFIRM_RIDE',
  REJECT_RIDE = 'REJECT_RIDE',
  WAIT_BIKER = 'WAIT_BIKER',
  BIKER_WAITING = 'BIKER_WAITING',
  BIKER_RECEIVED_PACKAGE = 'BIKER_RECEIVED_PACKAGE'
}

export enum PhaseBookingAfterRide {
  RIDE_COMPLETE_EVENT = 'RIDE_COMPLETE_EVENT'
}
